### PR TITLE
Virtualbox: use ubuntu 16.04.2 + fix vmdk name

### PR DESCRIPTION
**Pull request by abretaud**
Hi,
I wanted to generate a virtualbox VM with newer versions of galaxy/planemo/conda, and I had to make this little changes to make the `make virtualbox` work.

### CODE REVIEW

**Comment by jmchilton** [comment]
Thanks @abretaud - I have some more Conda updates in #98 coming soon if you are having problems with miniconda2 in the VM.

**Comment by jmchilton** [comment]
@abretaud I've had to revert the vmdk name locally to fix builds. The suffix of ``-disk1`` has always worked for me in the past under Linux and works for me currently under Mac OS X and VirtualBox 5.1.12. Any clue what is different between our setups? I reviewed the VirtualBox changelog for versions newer than 5.1.12 and nothing pops out (https://www.virtualbox.org/wiki/Changelog).

**Comment by abretaud** [comment]
Ah, that's odd...
I ran it again this morning with virtualbox 5.1.18 on linux and it still had the disk001 name.
Oh, just found this in the changelog (for 5.1.16): https://www.virtualbox.org/ticket/16402

**Comment by jmchilton** [comment]
Ahh - okay I will upgrade my virtualbox after my current run and let you know if that fixes it. Thanks!

**Pull request merged**
