### PR TITLE
reduce number of requested procs, add more vram

### PR DESCRIPTION
**Pull request by martenson**
vram setting found on a website of Slovak university :D http://nil.uniza.sk/virtualization/virtualbox/virtualbox-how-assign-more-video-memory-128mb

### CODE REVIEW

**Comment by martenson** [comment]
do I need to also modify the yaml file?

**Comment by dannon** [comment]
Definitely an improvement, but 128 seems a little high to me and I'm guessing it might cause problems for some laptop users.  I run Xubuntu at 2560x1440 with only 32mb of video memory and it's fine -- that might be a better default?

**Comment by martenson** [comment]
@dannon changed, thanks for feedback

**Comment by dannon** [comment]
Anytime.  Looks good to me!

**Comment by jmchilton** [comment]
Thanks! You should indeed change the yaml file and regenerate the JSON with `make packer`.

**Comment by martenson** [comment]
@jmchilton done

**Comment by bgruening** [comment]
:+1:

**Pull request merged**
