### PR TITLE
WIP: updates all over 

### PR DESCRIPTION
**Pull request by bgruening**
This PR includes all my local changes. Maybe this is useful for someone.
- add new qemu make target for OpenStack integration
- upgrade to Ubuntu 16.04
- Upgrade all packages during build + deactivate the auto-update during runtime
- include new locales
- ansible changes (sudo/become)

@davebx I'm not sure it's wise to upgrade Ubuntu before GCC. For example we need a new nginx-ppa build, but I hope here are a few changes that are useful for you.

@jmchilton is there any reason why you have choosen XFCE? GNOME has better gsettings integration and many small tweaks would be really easy with GNOME and it seems they are not as easy with XFCE.

### CODE REVIEW

**Comment by jmchilton** [comment]
Utterly fantastic @bgruening - a million thanks!

Regarding XFCE - I guess it is considered more lightweight? If you want to switch to gnome I am completely okay with that though.

Regarding to 16.04 - this seems fine to me - if the image builds I doubt there will be any problems internally.

**Comment by bgruening** [comment]
@jmchilton at the moment the only show stopper is a new nginx package and small node problems that can be fixed hopefully. I will work on this as time permits, just wanted to get this out to @davebx if he starts to work it.

**Comment by mvdbeek** [comment]
> @davebx I'm not sure it's wise to upgrade Ubuntu before GCC. For example we need a new nginx-ppa build, but I hope here are a few changes that are useful for you.

@bgruening 
https://launchpad.net/~m-vandenbeek/+archive/ubuntu/nginx-upload-store/+packages

Waiting for the publishing now ...

**Comment by bgruening** [comment]
Awesome! Have you heart anything from Nate and sharing an account?

**Comment by mvdbeek** [comment]
> Have you heart anything from Nate and sharing an account?

That would be surprising, given that I haven't asked ... :)

**Comment by bgruening** [comment]
Ok, this at least compiles for me know until the point Galaxy tries to fetch eggs :)
So progress here! Thanks @mvdbeek!

**Comment by jmchilton** [comment]
Is this ready to be merged then? I'm going to merge @davebx's PRs and I hope they don't cause a conflict.

**Comment by bgruening** [comment]
Not sure it's ready yet. Here is a small summary:
- Galaxy 16.04 is included
- xubuntu 16.04 is included with all updates including new postgresql
- It's building :) 
- I can run planemo

Things that need to be fixed:
- supervisord is not starting by default not yet looked at it

**Comment by jmchilton** [comment]
@bgruening Can you send me a link to image with supervisor not starting? I might be able to debug it. Alternatively, I can merge this and hope dockerhub gives me a new image to work with. I'll do that second one unless I here from you.

**Comment by bgruening** [comment]
Unfortunately not. Uploading the 4GB will take a day :(
But I can also spend some time this weekend on it.

**Comment by jmchilton** [comment]
This branch is looking fantastic - thanks for all the hard work!

**Comment by bgruening** [comment]
I'm getting greedy. `make docker` and `make virtualbox` are now working for me so I consider removing the WIP tag.
@davebx any comments? Can you also compile both versions?

**Comment by jmchilton** [comment]
Epic - thanks so much you too! Beer debt + several to each of you.

**Pull request merged**
