### PR TITLE
Update to 19.01

### PR DESCRIPTION
**Pull request by abretaud**
So here's an update of the virtualbox image to Galaxy 19.01 (in preparation for https://www.france-bioinformatique.fr/fr/evenements/elixir-galaxy-community-workshop-roscofffrance)
It also depends on https://github.com/galaxyproject/ansible-galaxy/pull/67
I generated the .ova and uploaded it to http://bipaa.genouest.org/data/public/galaxy/planemo-machine.ova, if it looks good to you, maybe https://images.galaxyproject.org/planemo/latest.ova could be updated with this one?

### CODE REVIEW

**Comment by abretaud** [comment]
(for now it's red because of https://github.com/galaxyproject/ansible-galaxy/pull/67)

**Comment by jmchilton** [comment]
Merged the ansible role and re-ran the Travis tests. Thanks so much for putting this together.

**Comment by abretaud** [comment]
Cool, green now!

**Comment by jmchilton** [comment]
Amazing, thanks so much!

**Comment by jmchilton** [comment]
Working on upgrading to this OVA but I don't seem to have access to the images server. Did this image go well during your training? Any critical bugs you encountered or can we re-use this for the GCC?

**Comment by jmchilton** [comment]
Also I'm getting a 403 - do you happen to have access to a link that is open to the public?

**Comment by bgruening** [comment]
It was public, I think it is just down. We do have holidays here in Europe. @abretaud will probably respond tomorrow.

Afaik this image was working.

**Comment by abretaud** [comment]
Hi! Sorry, I deleted it to free some space, I've just put it back online
I think it can be used for gcc yes, no specific problem

**Comment by jmchilton** [comment]
I couldn't get that image to download correctly - I did eventually with some retries but it had checksum issues then.

I rebuilt an image against master and it looks okay at first glance - the image is here http://images.galaxyproject.org/planemo/latest.ova.

**Pull request merged**
