### PR TITLE
Galaxy 16.04 updates

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
@jmchilton I still have the problem that `planemo test` is not working because the upload of files is not working in the planemo Galaxy instance. The upload in the supervisord Galaxy instance on `localhost` is working.
Same behaviour I have seen under 16.01. So I try to think this is a planemo issue here in the machine? Any thought?

**Comment by jmchilton** [comment]
Do you have a VM with these updates? I can try to debug the test problem?

**Comment by jmchilton** [comment]
Docker Hub has some very fresh images with planemo 0.25.1 that have this same issue - the problem is that planemo uses Galaxy's `config/job_conf.xml` which has handlers defined that differ in name from the one used by the test framework.

**Comment by bgruening** [comment]
@jmchilton here are some older ones but with the same problem: https://drive.google.com/folderview?id=0B2xSE9muunQPdXdfNVRIS09lWUU&usp=sharing

**Pull request merged**
