### PR TITLE
Various updates + CircleCI client

### PR DESCRIPTION
**Pull request by abretaud**
Hi,
With @cmonjeau, we're preparing for a small training session soon, so we've made these changes to generate an updated virtualbox image.
Now it's Galaxy 17.09, with the latest planemo and conda.
We also added the CircleCI client now that bioconda have switched to it
This is somewhat related to https://github.com/galaxyproject/training-material/pull/680

### CODE REVIEW

**Comment by bgruening** [comment]
Super cool @abretaud!

**Comment by bgruening** [comment]
And it all turned green :)
Ok for you @jmchilton?

**Comment by jmchilton** [comment]
More than okay - really super awesome in fact! Thanks so much @abretaud! 

If you generate a link for a clean virtualbox image based on this let me know and I'll download it to http://images.galaxyproject.org/planemo/.

**Comment by abretaud** [comment]
Thanks for merging, the virtualbox image is online at http://bipaa.genouest.org/data/public/galaxy/planemo-machine.ova

**Comment by abretaud** [comment]
(And it's also online at https://data-access.cesgo.org/index.php/s/HFrrtxbpjcmDCDx/download)
@cmonjeau ;)

**Comment by cmonjeau** [comment]
Thanks @abretaud :)

**Pull request merged**
